/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as FindHallRouteImport } from './routes/find-hall'
import { Route as FindExamRouteImport } from './routes/find-exam'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCalendarRouteImport } from './routes/_authenticated/calendar'
import { Route as AuthenticatedAuditRouteImport } from './routes/_authenticated/audit'
import { Route as AuthenticatedAdminsRouteImport } from './routes/_authenticated/admins'
import { Route as AuthenticatedVenuesIndexRouteImport } from './routes/_authenticated/venues/index'
import { Route as AuthenticatedConferenceHallsIndexRouteImport } from './routes/_authenticated/conference-halls/index'
import { Route as AuthenticatedConferenceBookingsIndexRouteImport } from './routes/_authenticated/conference-bookings/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedVenuesNewRouteImport } from './routes/_authenticated/venues/new'
import { Route as AuthenticatedVenuesIdRouteImport } from './routes/_authenticated/venues/$id'
import { Route as AuthenticatedConferenceHallsNewRouteImport } from './routes/_authenticated/conference-halls/new'
import { Route as AuthenticatedConferenceHallsIdRouteImport } from './routes/_authenticated/conference-halls/$id'
import { Route as AuthenticatedConferenceBookingsNewRouteImport } from './routes/_authenticated/conference-bookings/new'
import { Route as AuthenticatedConferenceBookingsIdRouteImport } from './routes/_authenticated/conference-bookings/$id'
import { Route as AuthenticatedBookingsNewRouteImport } from './routes/_authenticated/bookings/new'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings/$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const FindHallRoute = FindHallRouteImport.update({
  id: '/find-hall',
  path: '/find-hall',
  getParentRoute: () => rootRouteImport,
} as any)
const FindExamRoute = FindExamRouteImport.update({
  id: '/find-exam',
  path: '/find-exam',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCalendarRoute = AuthenticatedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditRoute = AuthenticatedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminsRoute = AuthenticatedAdminsRouteImport.update({
  id: '/admins',
  path: '/admins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenuesIndexRoute =
  AuthenticatedVenuesIndexRouteImport.update({
    id: '/venues/',
    path: '/venues/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenceHallsIndexRoute =
  AuthenticatedConferenceHallsIndexRouteImport.update({
    id: '/conference-halls/',
    path: '/conference-halls/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenceBookingsIndexRoute =
  AuthenticatedConferenceBookingsIndexRouteImport.update({
    id: '/conference-bookings/',
    path: '/conference-bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVenuesNewRoute = AuthenticatedVenuesNewRouteImport.update({
  id: '/venues/new',
  path: '/venues/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenuesIdRoute = AuthenticatedVenuesIdRouteImport.update({
  id: '/venues/$id',
  path: '/venues/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConferenceHallsNewRoute =
  AuthenticatedConferenceHallsNewRouteImport.update({
    id: '/conference-halls/new',
    path: '/conference-halls/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenceHallsIdRoute =
  AuthenticatedConferenceHallsIdRouteImport.update({
    id: '/conference-halls/$id',
    path: '/conference-halls/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenceBookingsNewRoute =
  AuthenticatedConferenceBookingsNewRouteImport.update({
    id: '/conference-bookings/new',
    path: '/conference-bookings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConferenceBookingsIdRoute =
  AuthenticatedConferenceBookingsIdRouteImport.update({
    id: '/conference-bookings/$id',
    path: '/conference-bookings/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsNewRoute =
  AuthenticatedBookingsNewRouteImport.update({
    id: '/bookings/new',
    path: '/bookings/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-exam': typeof FindExamRoute
  '/find-hall': typeof FindHallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/conference-bookings/$id': typeof AuthenticatedConferenceBookingsIdRoute
  '/conference-bookings/new': typeof AuthenticatedConferenceBookingsNewRoute
  '/conference-halls/$id': typeof AuthenticatedConferenceHallsIdRoute
  '/conference-halls/new': typeof AuthenticatedConferenceHallsNewRoute
  '/venues/$id': typeof AuthenticatedVenuesIdRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/conference-bookings/': typeof AuthenticatedConferenceBookingsIndexRoute
  '/conference-halls/': typeof AuthenticatedConferenceHallsIndexRoute
  '/venues/': typeof AuthenticatedVenuesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/find-exam': typeof FindExamRoute
  '/find-hall': typeof FindHallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admins': typeof AuthenticatedAdminsRoute
  '/audit': typeof AuthenticatedAuditRoute
  '/calendar': typeof AuthenticatedCalendarRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/conference-bookings/$id': typeof AuthenticatedConferenceBookingsIdRoute
  '/conference-bookings/new': typeof AuthenticatedConferenceBookingsNewRoute
  '/conference-halls/$id': typeof AuthenticatedConferenceHallsIdRoute
  '/conference-halls/new': typeof AuthenticatedConferenceHallsNewRoute
  '/venues/$id': typeof AuthenticatedVenuesIdRoute
  '/venues/new': typeof AuthenticatedVenuesNewRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/conference-bookings': typeof AuthenticatedConferenceBookingsIndexRoute
  '/conference-halls': typeof AuthenticatedConferenceHallsIndexRoute
  '/venues': typeof AuthenticatedVenuesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/find-exam': typeof FindExamRoute
  '/find-hall': typeof FindHallRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admins': typeof AuthenticatedAdminsRoute
  '/_authenticated/audit': typeof AuthenticatedAuditRoute
  '/_authenticated/calendar': typeof AuthenticatedCalendarRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/bookings/new': typeof AuthenticatedBookingsNewRoute
  '/_authenticated/conference-bookings/$id': typeof AuthenticatedConferenceBookingsIdRoute
  '/_authenticated/conference-bookings/new': typeof AuthenticatedConferenceBookingsNewRoute
  '/_authenticated/conference-halls/$id': typeof AuthenticatedConferenceHallsIdRoute
  '/_authenticated/conference-halls/new': typeof AuthenticatedConferenceHallsNewRoute
  '/_authenticated/venues/$id': typeof AuthenticatedVenuesIdRoute
  '/_authenticated/venues/new': typeof AuthenticatedVenuesNewRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/conference-bookings/': typeof AuthenticatedConferenceBookingsIndexRoute
  '/_authenticated/conference-halls/': typeof AuthenticatedConferenceHallsIndexRoute
  '/_authenticated/venues/': typeof AuthenticatedVenuesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/find-exam'
    | '/find-hall'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admins'
    | '/audit'
    | '/calendar'
    | '/dashboard'
    | '/notifications'
    | '/reports'
    | '/bookings/$id'
    | '/bookings/new'
    | '/conference-bookings/$id'
    | '/conference-bookings/new'
    | '/conference-halls/$id'
    | '/conference-halls/new'
    | '/venues/$id'
    | '/venues/new'
    | '/bookings/'
    | '/conference-bookings/'
    | '/conference-halls/'
    | '/venues/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/find-exam'
    | '/find-hall'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admins'
    | '/audit'
    | '/calendar'
    | '/dashboard'
    | '/notifications'
    | '/reports'
    | '/bookings/$id'
    | '/bookings/new'
    | '/conference-bookings/$id'
    | '/conference-bookings/new'
    | '/conference-halls/$id'
    | '/conference-halls/new'
    | '/venues/$id'
    | '/venues/new'
    | '/bookings'
    | '/conference-bookings'
    | '/conference-halls'
    | '/venues'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/find-exam'
    | '/find-hall'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admins'
    | '/_authenticated/audit'
    | '/_authenticated/calendar'
    | '/_authenticated/dashboard'
    | '/_authenticated/notifications'
    | '/_authenticated/reports'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/bookings/new'
    | '/_authenticated/conference-bookings/$id'
    | '/_authenticated/conference-bookings/new'
    | '/_authenticated/conference-halls/$id'
    | '/_authenticated/conference-halls/new'
    | '/_authenticated/venues/$id'
    | '/_authenticated/venues/new'
    | '/_authenticated/bookings/'
    | '/_authenticated/conference-bookings/'
    | '/_authenticated/conference-halls/'
    | '/_authenticated/venues/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FindExamRoute: typeof FindExamRoute
  FindHallRoute: typeof FindHallRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-hall': {
      id: '/find-hall'
      path: '/find-hall'
      fullPath: '/find-hall'
      preLoaderRoute: typeof FindHallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-exam': {
      id: '/find-exam'
      path: '/find-exam'
      fullPath: '/find-exam'
      preLoaderRoute: typeof FindExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/calendar': {
      id: '/_authenticated/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthenticatedCalendarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit': {
      id: '/_authenticated/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthenticatedAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admins': {
      id: '/_authenticated/admins'
      path: '/admins'
      fullPath: '/admins'
      preLoaderRoute: typeof AuthenticatedAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venues/': {
      id: '/_authenticated/venues/'
      path: '/venues'
      fullPath: '/venues/'
      preLoaderRoute: typeof AuthenticatedVenuesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conference-halls/': {
      id: '/_authenticated/conference-halls/'
      path: '/conference-halls'
      fullPath: '/conference-halls/'
      preLoaderRoute: typeof AuthenticatedConferenceHallsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conference-bookings/': {
      id: '/_authenticated/conference-bookings/'
      path: '/conference-bookings'
      fullPath: '/conference-bookings/'
      preLoaderRoute: typeof AuthenticatedConferenceBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venues/new': {
      id: '/_authenticated/venues/new'
      path: '/venues/new'
      fullPath: '/venues/new'
      preLoaderRoute: typeof AuthenticatedVenuesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/venues/$id': {
      id: '/_authenticated/venues/$id'
      path: '/venues/$id'
      fullPath: '/venues/$id'
      preLoaderRoute: typeof AuthenticatedVenuesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conference-halls/new': {
      id: '/_authenticated/conference-halls/new'
      path: '/conference-halls/new'
      fullPath: '/conference-halls/new'
      preLoaderRoute: typeof AuthenticatedConferenceHallsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conference-halls/$id': {
      id: '/_authenticated/conference-halls/$id'
      path: '/conference-halls/$id'
      fullPath: '/conference-halls/$id'
      preLoaderRoute: typeof AuthenticatedConferenceHallsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conference-bookings/new': {
      id: '/_authenticated/conference-bookings/new'
      path: '/conference-bookings/new'
      fullPath: '/conference-bookings/new'
      preLoaderRoute: typeof AuthenticatedConferenceBookingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conference-bookings/$id': {
      id: '/_authenticated/conference-bookings/$id'
      path: '/conference-bookings/$id'
      fullPath: '/conference-bookings/$id'
      preLoaderRoute: typeof AuthenticatedConferenceBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/new': {
      id: '/_authenticated/bookings/new'
      path: '/bookings/new'
      fullPath: '/bookings/new'
      preLoaderRoute: typeof AuthenticatedBookingsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminsRoute: typeof AuthenticatedAdminsRoute
  AuthenticatedAuditRoute: typeof AuthenticatedAuditRoute
  AuthenticatedCalendarRoute: typeof AuthenticatedCalendarRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedBookingsNewRoute: typeof AuthenticatedBookingsNewRoute
  AuthenticatedConferenceBookingsIdRoute: typeof AuthenticatedConferenceBookingsIdRoute
  AuthenticatedConferenceBookingsNewRoute: typeof AuthenticatedConferenceBookingsNewRoute
  AuthenticatedConferenceHallsIdRoute: typeof AuthenticatedConferenceHallsIdRoute
  AuthenticatedConferenceHallsNewRoute: typeof AuthenticatedConferenceHallsNewRoute
  AuthenticatedVenuesIdRoute: typeof AuthenticatedVenuesIdRoute
  AuthenticatedVenuesNewRoute: typeof AuthenticatedVenuesNewRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedConferenceBookingsIndexRoute: typeof AuthenticatedConferenceBookingsIndexRoute
  AuthenticatedConferenceHallsIndexRoute: typeof AuthenticatedConferenceHallsIndexRoute
  AuthenticatedVenuesIndexRoute: typeof AuthenticatedVenuesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminsRoute: AuthenticatedAdminsRoute,
  AuthenticatedAuditRoute: AuthenticatedAuditRoute,
  AuthenticatedCalendarRoute: AuthenticatedCalendarRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedBookingsNewRoute: AuthenticatedBookingsNewRoute,
  AuthenticatedConferenceBookingsIdRoute:
    AuthenticatedConferenceBookingsIdRoute,
  AuthenticatedConferenceBookingsNewRoute:
    AuthenticatedConferenceBookingsNewRoute,
  AuthenticatedConferenceHallsIdRoute: AuthenticatedConferenceHallsIdRoute,
  AuthenticatedConferenceHallsNewRoute: AuthenticatedConferenceHallsNewRoute,
  AuthenticatedVenuesIdRoute: AuthenticatedVenuesIdRoute,
  AuthenticatedVenuesNewRoute: AuthenticatedVenuesNewRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedConferenceBookingsIndexRoute:
    AuthenticatedConferenceBookingsIndexRoute,
  AuthenticatedConferenceHallsIndexRoute:
    AuthenticatedConferenceHallsIndexRoute,
  AuthenticatedVenuesIndexRoute: AuthenticatedVenuesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FindExamRoute: FindExamRoute,
  FindHallRoute: FindHallRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
